#
# Module manifest for module 'Packaging'
#
# Generated by: Joel 'Jaykul' Bennett <Jaykul@HuddledMasses.org>
#
# Generated on: 6/10/2013
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Packaging.psm1'

# Version number of this module.
ModuleVersion = '1.0.9'

# ID used to uniquely identify this module
GUID = '88c6579a-27b2-41c8-86c6-cd23acb791e9'

# Author of this module
Author = 'Joel ''Jaykul'' Bennett <Jaykul@HuddledMasses.org>'

# Company or vendor of this module
CompanyName = 'http://HuddledMasses.org'

# Copyright statement for this module
Copyright = 'Copyright (c) 2013 by Joel Bennett, all rights reserved.'

# Description of the functionality provided by this module
Description = 'Packaging Module for PowerShell Modules'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = '4.0'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'WindowsBase', 'PresentationFramework'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('.\Configuration.psm1', 
               '.\Installation.psm1')

# Functions to export from this module
FunctionsToExport = 'New-ModulePackage', 'Install-ModulePackage', 'Get-ModuleInfo', 
               'Update-ModuleInfo', 'Test-ConfigData', 'Get-ConfigData', 
               'Set-ConfigData', 'Get-SpecialFolder', 'Invoke-Web', 'Get-ConfigData', 
               'Get-ModuleInfo', 'Get-SpecialFolder', 'Install-ModulePackage', 
               'Set-ConfigData', 'Test-ConfigData', 'Update-ModuleInfo', 
               'Update-Module'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module.
# ModuleList = @()

# List of all files packaged with this module
FileList = '.\Packaging.psdxml', '.\Packaging.psd1', '.\Packaging.psm1', 
               '.\Packaging.ini', '.\Configuration.psm1', '.\InvokeWeb.psm1', 
               '.\Source\AssemblyInfo.cs', '.\Source\ModuleId.cs', 
               '.\Source\StringList.cs', '.\Source\ModuleInfo.cs', 
               '.\Source\ModuleManifest.cs', '.\Source\UnitTests.cs', 
               '.\Source\Version.cs', '.\Source\VersionTypeConverter.cs', 
               '.\Installation.psm1'

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

